packages:
  - server

injectWorkspacePackages: true
enableGlobalVirtualStore: false
autoInstallPeers: false
dedupePeerDependents: false
resolvePeersFromWorkspaceRoot: false
syncInjectedDepsAfterScripts: []
strictPeerDependencies: false
strictDepBuilds: true
strictStorePkgContentCheck: true
verifyStoreIntegrity: true
verifyDepsBeforeRun: error
dangerouslyAllowAllBuilds: false

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true

patchedDependencies:
  '@angular/build@22.0.8': patches/@angular__build@22.0.8.patch
